version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@SS
      MYSQL_DATABASE: localdb
      MYSQL_USER: sa
      MYSQL_PASSWORD: P@SS
    ports:
      - "3307:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -usa -pP@SS || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 70s
    volumes:
      - mysql_data:/var/lib/mysql

  webapi:
    build: .
    image: webapi:0.1
    container_name: webapi
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=localdb;User=sa;Password=P@SS;
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
